// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw9N3_LBkEjpGVAL1LFev2Fzp4_WTWNTY',
    appId: '1:1073454404718:web:61679607b8d61e9032027f',
    messagingSenderId: '1073454404718',
    projectId: 'kivi-2964a',
    authDomain: 'kivi-2964a.firebaseapp.com',
    databaseURL: 'https://kivi-2964a-default-rtdb.firebaseio.com',
    storageBucket: 'kivi-2964a.firebasestorage.app',
    measurementId: 'G-LYK841Z3K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyxfTj9ImPh7iAof5KQrgrL60D_bB3Zs',
    appId: '1:1073454404718:android:1a36a7de1dd4a7d732027f',
    messagingSenderId: '1073454404718',
    projectId: 'kivi-2964a',
    databaseURL: 'https://kivi-2964a-default-rtdb.firebaseio.com',
    storageBucket: 'kivi-2964a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM8JYJLXiFJ_7uXyOogkKtlxB5vwPa8Ic',
    appId: '1:1073454404718:ios:96f26661697b2dda32027f',
    messagingSenderId: '1073454404718',
    projectId: 'kivi-2964a',
    databaseURL: 'https://kivi-2964a-default-rtdb.firebaseio.com',
    storageBucket: 'kivi-2964a.firebasestorage.app',
    iosBundleId: 'com.example.kivi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM8JYJLXiFJ_7uXyOogkKtlxB5vwPa8Ic',
    appId: '1:1073454404718:ios:96f26661697b2dda32027f',
    messagingSenderId: '1073454404718',
    projectId: 'kivi-2964a',
    databaseURL: 'https://kivi-2964a-default-rtdb.firebaseio.com',
    storageBucket: 'kivi-2964a.firebasestorage.app',
    iosBundleId: 'com.example.kivi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw9N3_LBkEjpGVAL1LFev2Fzp4_WTWNTY',
    appId: '1:1073454404718:web:000ece6a03505d4e32027f',
    messagingSenderId: '1073454404718',
    projectId: 'kivi-2964a',
    authDomain: 'kivi-2964a.firebaseapp.com',
    databaseURL: 'https://kivi-2964a-default-rtdb.firebaseio.com',
    storageBucket: 'kivi-2964a.firebasestorage.app',
    measurementId: 'G-BNFF5CYYC9',
  );
}
